name: Test BDR Deployment

on:
  workflow_dispatch:
  workflow_call:

runs:
  using: "composite"
  steps:
    - name: Export Credentials to download TPAexec and BDR
      run: | 
        export EDB_SUBSCRIPTION_TOKEN=${{ env.EDB_SUBSCRIPTION_TOKEN }}
        export TPA_2Q_SUBSCRIPTION_TOKEN=${{ env.TPA_2Q_SUBSCRIPTION_TOKEN }}
        export EDB_REPO_CREDENTIALS_FILE=~/.edbrepocred
        echo ${{ env.EDB_REPO_CREDENTIALS }} > ~/.edbrepocred
        chmod 600 ~/.edbrepocred
      shell: bash
    
    - name: Install TPAexec
      run: |
        curl https://techsupport.enterprisedb.com/api/repository/${{ env.TPA_2Q_SUBSCRIPTION_TOKEN }}/products/tpa/release/deb | sudo bash
        sudo apt-get -y install tpaexec
      shell: bash
      
    - name: Set up TPAexec 
      run: |
        sudo /opt/EDB/TPA/bin/tpaexec setup
        sudo /opt/EDB/TPA/bin/tpaexec selftest
      shell: bash
      
    - name: Configure BDR cluster
      run: |
        sudo /opt/EDB/TPA/bin/tpaexec configure test \
        --architecture BDR-Always-ON \
        --layout bronze \
        --platform docker \
        --bdr-version 3 \
        --harp-consensus-protocol bdr \
        --postgresql \
        --postgres-version 14 \
        --no-git \
        --hostnames-unsorted
      shell: bash
    
    - name: Provision BDR cluster
      run: |
        sudo /opt/EDB/TPA/bin/tpaexec provision test
      shell: bash
      
    - name: Deploy BDR cluster
      run: |
        sudo -E /opt/EDB/TPA/bin/tpaexec deploy test
      shell: bash
    
    - name: Verify the BDR cluster checks
      run: |
        docker exec --user postgres kaboom psql -d bdrdb -c "SELECT * FROM bdr.monitor_group_raft();"
        docker exec --user postgres kaftan psql -d bdrdb -c "SELECT * FROM bdr.monitor_group_raft();"
        docker exec --user postgres kaolin psql -d bdrdb -c "SELECT * FROM bdr.monitor_group_raft();"

        docker exec --user postgres kaboom psql -d bdrdb -c "SELECT * FROM bdr.monitor_group_versions();"
        docker exec --user postgres kaftan psql -d bdrdb -c "SELECT * FROM bdr.monitor_group_versions();"
        docker exec --user postgres kaolin psql -d bdrdb -c "SELECT * FROM bdr.monitor_group_versions();"

        docker exec --user postgres kaboom psql -d bdrdb -c "SELECT * FROM bdr.monitor_local_replslots();"
        docker exec --user postgres kaftan psql -d bdrdb -c "SELECT * FROM bdr.monitor_local_replslots();"
        docker exec --user postgres kaolin psql -d bdrdb -c "SELECT * FROM bdr.monitor_local_replslots();"
      shell: bash
